name: "sh-checker"
description: "Run shellcheck and/or shfmt on all shell script files and include commentaries, there is a exclude parameter"
author: "luizm"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "terminal"
  color: "black"
